### ISSUE TITLE
It's no one's turn

### ISSUE THREAD

**Issue by katiecs3** [byucs340ta/Fall2018#219] opened 2018-11-28 02:34 UTC
After starting a new game both clients get the error "It's not your turn."

**Comment by cameronconradt** [comment] 2018-11-28 03:48
This happened with me when one player didn't select any destination cards and just pressed the back button.

**Comment by andrewblomquist** [comment] 2018-11-28 16:19
Seems like it's related to / is a duplicate of #216 and #212

**Closed** 2018-11-30 16:54 UTC
Labels: P2: Halts Gameplay, Team 5
