### ISSUE TITLE
Game selection screen not updating for second player

### ISSUE THREAD

**Issue by cameronconradt** [byucs340ta/Fall2018#248] opened 2018-11-28 03:52 UTC
The new games only show up locally or after logging out and back in.

**Comment by andrewblomquist** [comment] 2018-11-28 18:34
#282 is a duplicate of this.

This'll be tough to fix/reproduce without looking over people's shoulders. This isn't a problem when we run it ourselves.

**Closed** 2018-11-30 16:54 UTC
Labels: Not going to fix, P3: Affects Gameplay, Team 5
