### ISSUE TITLE
more server down issues 

### ISSUE THREAD

**Issue by BrainRayChristensen** [byucs340ta/Fall2018#143] opened 2018-11-27 20:39 UTC
Server went down. I was on the main menu screen. Back button is disabled and the logout command failed. Thus, stuck on that screen. I had to restart the app.

**Comment by marceloarchiza** [comment] 2018-11-28 05:59
This is a duplicate of bug #142 So I am closing it.

**Closed by marceloarchiza** 2018-11-28 05:59 UTC
Labels: P2: Halts Gameplay, Team 15
